# Generated by Django 4.2.16 on 2024-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
